CREATE TABLE TB_ESTADO (
    SIGLA_ESTADO char(2),
	NOME_ESTADO varchar(40)
)

CREATE TABLE TB_CLASSE (
    ID_CLASSE smallint,
	ID_ANDAR smallint
)

CREATE TABLE TB_ALUNO (
    COD_ALUNO char(2),
	NOME_ALUNO varchar(45),
	END_ALUNO varchar(100),
	SIGLA_ESTADO char(2),
	ID_CLASSE smallint
)

CREATE TABLE TB_ALUNO_DISCIPLINA (
    COD_ALUNO char(2),
	ID_DISCIPLINA char(3),
	NOTA_ALUNO smallint
)

CREATE TABLE TB_DISCIPLINA (
	ID_DISCIPLINA char(3),
	NOME_DISCIPLINA varchar(15),
	ID_PROFESSOR_DISCIPLINA char(3),
	NOTA_MINIMA_DISCIPLINA smallint
)

CREATE TABLE TB_PROFESSOR (
    ID_PROFESSOR char(3),
	NOME_PROFESSOR varchar(25)
)