ALTER TABLE TB_ALUNO
ADD CONSTRAINT chave_estrangeira
FOREIGN KEY (SIGLA_ESTADO)
REFERENCES TB_ESTADO (SIGLA_ESTADO);

ALTER TABLE TB_ALUNO
ADD CONSTRAINT chave_estrangeira_classe
FOREIGN KEY (ID_CLASSE)
REFERENCES TB_CLASSE (ID_CLASSE);

ALTER TABLE TB_ALUNO_DISCIPLINA 
ADD CONSTRAINT chave_estrangeira_cod_aluno
FOREIGN KEY (COD_ALUNO)
REFERENCES TB_ALUNO (COD_ALUNO);

ALTER TABLE TB_ALUNO_DISCIPLINA 
ADD CONSTRAINT chave_estrangeira_id_disciplina
FOREIGN KEY (ID_DISCIPLINA)
REFERENCES TB_DISCIPLINA (ID_DISCIPLINA);

ALTER TABLE TB_DISCIPLINA 
ADD CONSTRAINT chave_estrangeira_id_professor
FOREIGN KEY (ID_PROFESSOR_DISCIPLINA)
REFERENCES TB_PROFESSOR (ID_PROFESSOR);

