INSERT INTO TB_PROFESSOR (ID_PROFESSOR, NOME_PROFESSOR)
VALUES ('JOI', 'JOILSON CARDOSO');

INSERT INTO TB_PROFESSOR (ID_PROFESSOR, NOME_PROFESSOR)
VALUES ('OSE', 'OSEAS SANTANA');

INSERT INTO TB_PROFESSOR (ID_PROFESSOR, NOME_PROFESSOR)
VALUES ('VIT', 'VITOR VASCONCELOS');

INSERT INTO TB_PROFESSOR (ID_PROFESSOR, NOME_PROFESSOR)
VALUES ('FER', 'JOSE ROBERTO FERROLI');

INSERT INTO TB_PROFESSOR (ID_PROFESSOR, NOME_PROFESSOR)
VALUES ('LIM', 'VALMIR LIMA');

INSERT INTO TB_PROFESSOR (ID_PROFESSOR, NOME_PROFESSOR)
VALUES ('EDS', 'EDSON SILVA');

INSERT INTO TB_PROFESSOR (ID_PROFESSOR, NOME_PROFESSOR)
VALUES ('WAG', 'WAGNER OKIDA');
