INSERT INTO TB_ALUNO (COD_ALUNO, NOME_ALUNO, END_ALUNO, SIGLA_ESTADO)
VALUES ('1', 'ANTONIO CARLOS PENTEADO', 'RUA X', 'SP');

INSERT INTO TB_ALUNO (COD_ALUNO, NOME_ALUNO, END_ALUNO, SIGLA_ESTADO)
VALUES ('2', 'AUROMIR DA SILVA VALDEVINO', 'RUA W', 'SP');

INSERT INTO TB_ALUNO (COD_ALUNO, NOME_ALUNO, END_ALUNO, SIGLA_ESTADO)
VALUES ('3', 'ANDRE COSTA', 'RUA T', 'SP');

INSERT INTO TB_ALUNO (COD_ALUNO, NOME_ALUNO, END_ALUNO, SIGLA_ESTADO)
VALUES ('4', 'ROBERTO SOARES DE MENEZES', 'RUA BW', 'SP');

INSERT INTO TB_ALUNO (COD_ALUNO, NOME_ALUNO, END_ALUNO, SIGLA_ESTADO)
VALUES ('5', 'DANIA', 'RUA CCC', 'SP');

INSERT INTO TB_ALUNO (COD_ALUNO, NOME_ALUNO, END_ALUNO, SIGLA_ESTADO)
VALUES ('6', 'CARLOS MAGALHAES', 'RUA SP', 'SP');

INSERT INTO TB_ALUNO (COD_ALUNO, NOME_ALUNO, END_ALUNO, SIGLA_ESTADO)
VALUES ('7', 'MARCELO RAUBA', 'RUA SAO LUIS', 'SP');

INSERT INTO TB_ALUNO (COD_ALUNO, NOME_ALUNO, END_ALUNO, SIGLA_ESTADO)
VALUES ('8', 'FERNANDO', 'RUA COUNTYR', 'SP');

INSERT INTO TB_ALUNO (COD_ALUNO, NOME_ALUNO, END_ALUNO, SIGLA_ESTADO)
VALUES ('9', 'WALMIR BURIN', 'RUA SSISIS', 'SP');