ALTER TABLE TB_ESTADO
ADD CONSTRAINT chave_primaria
PRIMARY KEY (SIGLA_ESTADO);

ALTER TABLE TB_CLASSE
ADD CONSTRAINT chave_primaria
PRIMARY KEY (ID_CLASSE);

ALTER TABLE TB_ALUNO
ADD CONSTRAINT chave_primaria
PRIMARY KEY (COD_ALUNO);

ALTER TABLE TB_DISCIPLINA
ADD CONSTRAINT chave_primaria
PRIMARY KEY (ID_DISCIPLINA);

ALTER TABLE TB_PROFESSOR
ADD CONSTRAINT chave_primaria
PRIMARY KEY (ID_PROFESSOR);

