SELECT COUNT(CodFornec) FROM TB_FORNEC 

SELECT COUNT(CidadeFornec) FROM TB_FORNEC
GROUP BY CidadeFornec

SELECT COUNT(CodFornec) FROM TB_FORNEC
WHERE CidadeFornec IS NOT NULL 

SELECT MAX(QtdeEmbarc) FROM TB_EMBARQ

SELECT QtdeEmbarc
FROM TB_EMBARQ E
INNER JOIN TB_FORNEC F
ON E.CodFornec = F.CodFornec 

SELECT QtdeEmbarc
FROM TB_EMBARQ
WHERE QtdeEmbarc > 300
GROUP BY QtdeEmbarc 

SELECT QtdeEmbarc
FROM TB_EMBARQ E
INNER JOIN TB_PECA P
ON E.CodPeca  = P.CodPeca 
WHERE CorPeca = 'CINZA'

SELECT QtdeEmbarc
FROM TB_EMBARQ E
INNER JOIN TB_FORNEC F
ON E.CodFornec = F.CodFornec 
ORDER BY QtdeEmbarc DESC
