SELECT NOME_ALUNO, ID_CLASSE FROM TB_ALUNO
ORDER BY NOME_ALUNO 

SELECT NOME_ALUNO, ID_CLASSE FROM TB_ALUNO
ORDER BY NOME_ALUNO DESC 

SELECT M.COD_ALUNO 
FROM TB_ALUNO_DISCIPLINA AS M
JOIN TB_ALUNO_DISCIPLINA AS P
ON M.COD_ALUNO = P.COD_ALUNO 
WHERE (M.ID_DISCIPLINA = 'MAT' AND P.ID_DISCIPLINA = 'POR')


