SELECT N.NOME_ALUNO 
FROM TB_ALUNO AS N
JOIN (SELECT DISTINCT COD_ALUNO FROM TB_ALUNO_DISCIPLINA
WHERE ID_DISCIPLINA = 'POR' OR ID_DISCIPLINA = 'MAT') AS C
ON N.COD_ALUNO = C.COD_ALUNO 

SELECT N.NOME_ALUNO, END_ALUNO 
FROM TB_ALUNO AS N
JOIN TB_ALUNO_DISCIPLINA AS C
ON N.COD_ALUNO = C.COD_ALUNO 
WHERE C.ID_DISCIPLINA = 'FIS'


